### ISSUE TITLE
Unable to compile in macos

### ISSUE THREAD

**Issue by galdolber** [smasher164/staticjni#1]
I'm getting the following error using GraalVM 20.2.0(11.0.8.0.2):

```

Linker command output:
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.1.0

```

```
Undefined symbols for architecture x86_64:
  "_Java_HelloWorld_print", referenced from:
      ___svm_vm_target_platform in HelloWorld.o
ld: symbol(s) not found for architecture x86_64
```

Any idea what could be wrong?

**Comment by smasher164** [comment]
- Are you sure you have a `native.o` file and `libNative.a` generated?
- Do they have `Java_HelloWorld_print` exported? What happens if you run `nm`?
For instance, I see
```
$ nm libNative.a

libNative.a(native.o):
0000000000000000 T _Java_HelloWorld_print
                 U _printf
```

**Comment by galdolber** [comment]
I was missing the 4th step!
ar rcs libNative.a native.o
Thank you!
